services:
    Dmishh\SettingsBundle\Manager\SettingsManagerInterface: '@Dmishh\SettingsBundle\Manager\SettingsManager'

    Dmishh\SettingsBundle\Manager\SettingsManager:
        arguments: [ '@doctrine.orm.entity_manager', '@Dmishh\SettingsBundle\Serializer\SerializerInterface', ~ ]

    Dmishh\SettingsBundle\Manager\CachedSettingsManager:
        arguments: [ '@Dmishh\SettingsBundle\Manager\SettingsManager', ~, ~ ]

    Dmishh\SettingsBundle\Serializer\SerializerInterface:
        class: Dmishh\SettingsBundle\Serializer\PhpSerializer
        factory: Dmishh\SettingsBundle\Serializer\SerializerFactory::create
        arguments: ['%settings_manager.serialization%']

    Dmishh\SettingsBundle\Form\Type\SettingsType:
        arguments: [ ~ ]
        tags:
            - { name: form.type }

    Dmishh\SettingsBundle\Twig\SettingsExtension:
        arguments: [ '@Dmishh\SettingsBundle\Manager\SettingsManagerInterface' ]
        tags:
            - { name: twig.extension }

    Dmishh\SettingsBundle\Controller\SettingsController:
        public: true
        autowire: true
        tags: ['container.service_subscriber']
        arguments:
            - '@translator'
            - '@Dmishh\SettingsBundle\Manager\SettingsManagerInterface'
            - ~ # template
            - ~ # manage own settings
            - ~ # security role
